# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to="products/"),
        ),
    ]
