apiVersion: v1
kind: Secret
metadata:
  name: store-ai-secret
  namespace: store-ai
type: Opaque
stringData:
  DJANGO_SECRET_KEY: change-me
  POSTGRES_PASSWORD: change-me
  OPENROUTER_API_KEY: change-me
